xoeoro_picturecut_upload:
    pattern:  /upload
    defaults: { _controller: XoeoroPictureCutBundle:Upload:index }
    options:
        expose: true

xoeoro_picturecut_crop:
    pattern:  /crop
    defaults: { _controller: XoeoroPictureCutBundle:Crop:index }
    options:
        expose: true

xoeoro_picturecut_window:
    pattern:  /window/{mode}
    defaults: { _controller: XoeoroPictureCutBundle:Window:index }
    requirements:
        mode:  bootstrap|jqueryui|popstyle
    options:
        expose: true