parameters:
    xoeoro.picturecut.file_base_path: "%kernel.root_dir%/../web/uploads/picturecut/"
    xoeoro.picturecut.web_base_path: "/uploads/picturecut/"

services:
    xoeoro.picturecut:
        class: Xoeoro\PictureCutBundle\Library\PictureCut
        arguments:
          - file_base_path: '%xoeoro.picturecut.file_base_path%'
            web_base_path: '%xoeoro.picturecut.web_base_path%'
            request: '@request'
        scope: request